import { useEffect, useState } from "react";
import api from "../../api/client";
import { useAuth } from "../../context/AuthContext";
import { PageHeader, EmptyState, Badge } from "../../components/DashboardBits";

const STATUS_TONE = { PAID: "success", PARTIAL: "warn", UNPAID: "default", OVERDUE: "danger" };

function StudentFeeView() {
  const [slips, setSlips] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.get("/fees/me").then(({ data }) => setSlips(data)).finally(() => setLoading(false));
  }, []);

  return (
    <div>
      <PageHeader title="My Fee Status" subtitle="Slips generated by the Accounts office." />
      {loading ? (
        <div className="text-sm text-slate">Loading…</div>
      ) : slips.length === 0 ? (
        <EmptyState message="No fee slips issued yet." />
      ) : (
        <div className="card overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="text-left text-slate border-b border-line">
                <th className="py-2 pr-4">Month</th>
                <th className="py-2 pr-4">Amount (PKR)</th>
                <th className="py-2 pr-4">Due Date</th>
                <th className="py-2">Status</th>
              </tr>
            </thead>
            <tbody>
              {slips.map((s) => (
                <tr key={s.id} className="border-b border-line last:border-0">
                  <td className="py-3 pr-4">{s.month}</td>
                  <td className="py-3 pr-4">{Number(s.amount).toLocaleString()}</td>
                  <td className="py-3 pr-4">{new Date(s.dueDate).toLocaleDateString()}</td>
                  <td className="py-3"><Badge tone={STATUS_TONE[s.status]}>{s.status}</Badge></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

function AccountantFeeView() {
  const [slips, setSlips] = useState([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState("");

  function load() {
    setLoading(true);
    api.get("/fees", { params: filter ? { status: filter } : {} }).then(({ data }) => setSlips(data)).finally(() => setLoading(false));
  }

  useEffect(load, [filter]);

  async function markPaid(id) {
    await api.patch(`/fees/${id}/mark-paid`);
    load();
  }

  return (
    <div>
      <PageHeader
        title="Fee Management"
        subtitle="Generate slips, track payment status, and follow up on defaulters."
        action={
          <select className="input w-auto" value={filter} onChange={(e) => setFilter(e.target.value)}>
            <option value="">All statuses</option>
            <option value="UNPAID">Unpaid</option>
            <option value="PARTIAL">Partial</option>
            <option value="PAID">Paid</option>
            <option value="OVERDUE">Overdue</option>
          </select>
        }
      />
      {loading ? (
        <div className="text-sm text-slate">Loading…</div>
      ) : slips.length === 0 ? (
        <EmptyState message="No fee slips match this filter." />
      ) : (
        <div className="card overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="text-left text-slate border-b border-line">
                <th className="py-2 pr-4">Student</th>
                <th className="py-2 pr-4">Class</th>
                <th className="py-2 pr-4">Amount</th>
                <th className="py-2 pr-4">Due Date</th>
                <th className="py-2 pr-4">Status</th>
                <th className="py-2"></th>
              </tr>
            </thead>
            <tbody>
              {slips.map((s) => (
                <tr key={s.id} className="border-b border-line last:border-0">
                  <td className="py-3 pr-4">{s.student.user.name}</td>
                  <td className="py-3 pr-4">{s.student.class?.name || "—"}</td>
                  <td className="py-3 pr-4">{Number(s.amount).toLocaleString()}</td>
                  <td className="py-3 pr-4">{new Date(s.dueDate).toLocaleDateString()}</td>
                  <td className="py-3 pr-4"><Badge tone={STATUS_TONE[s.status]}>{s.status}</Badge></td>
                  <td className="py-3">
                    {s.status !== "PAID" && (
                      <button onClick={() => markPaid(s.id)} className="text-xs text-brass hover:text-ink font-medium">
                        Mark Paid
                      </button>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

export default function Fees() {
  const { user } = useAuth();
  return user.role === "STUDENT" ? <StudentFeeView /> : <AccountantFeeView />;
}
